__author__ = "Kristina Sungeun Song"
__email__ = "kristina.song@usherbrooke.ca"


##### store paths and user-specific variables #####
configfile: "config/config.yaml"


#############################
## Load rules
#############################

include: "rules/download_wget.smk" # download FASTQ files via wget (faster but need to get url from SRA explorer)
include: "rules/preprocessing.smk"
include: "rules/mapping.smk"


rule all:
    input:
        ### STEP 1 ###
        # Download FASTQ files via wget -- profile_local
        #fq = "resources/fastq/download_status.txt",
        # Git repos -- use profile_local
        #icSHAPE_git = directory('resources/icSHAPE'),
        #CoCo_git = directory('resources/CoCo'),
        ### STEP 2 ###
        # FastQC
        PARIS_qc = expand("results/fastqc/{qc_type}/PARIS/{accession}_fastqc.html",accession=config['PARIS'],qc_type=['raw','preprocessed']),
        PARIS2_qc = expand("results/fastqc/{qc_type}/PARIS2/{accession}_fastqc.html",accession=config['PARIS2'],qc_type=['raw','preprocessed']),
        LIGR_seq_qc = expand("results/fastqc/{qc_type}/LIGR_seq/{accession}_fastqc.html",accession=config['LIGR_seq'],qc_type=['raw','preprocessed']),
        SPLASH_qc = expand("results/fastqc/{qc_type}/SPLASH/{accession}_fastqc.html",accession=config['SPLASH'],qc_type=['raw','preprocessed']),
        # DuplexDiscovereR
        dg = "results/duplexdiscoverer/all_dgs.tsv"
